# Generated by Django 3.2.9 on 2021-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0002_statususerslocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='users',
        ),
        migrations.AlterField(
            model_name='statususerslocations',
            name='status',
            field=models.IntegerField(choices=[(1, 'En attente'), (2, 'Actif'), (3, 'Rejeté'), (4, 'Désactivé'), (5, "Annulé par l'utilisateur")], default=1),
        ),
    ]
