# Generated by Django 3.2.9 on 2021-11-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0003_auto_20211102_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Manager')], default=2, max_length=255),
        ),
    ]
