# Generated by Django 3.2.9 on 2021-11-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0004_auto_20211102_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
