# Generated by Django 3.2.9 on 2021-11-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0005_remove_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='manager',
            new_name='manager_location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_locations', to='monespace.location'),
        ),
    ]
