# Generated by Django 3.2.9 on 2021-11-11 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0005_statususerslocations_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsStatusUsersLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'En attente'), (2, 'Actif'), (3, 'Rejeté'), (4, 'Désactivé'), (5, "Annulé par l'utilisateur")], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs_location_status_user', to='monespace.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_user_status_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
