# Generated by Django 3.2.9 on 2021-11-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0006_logsstatususerslocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeesevents',
            name='parent_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttendeesEvents_event', to='monespace.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_locations', to='monespace.location'),
        ),
        migrations.AlterField(
            model_name='eventexceptioncancelledrescheduled',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_exceptions_locations', to='monespace.location'),
        ),
        migrations.AlterField(
            model_name='eventexceptioncancelledrescheduled',
            name='parent_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventExceptionCancelledRescheduled_event', to='monespace.event'),
        ),
    ]
