# Generated by Django 3.2.9 on 2021-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0006_auto_20211102_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Manager')], default=2, max_length=255),
        ),
    ]
