# Generated by Django 3.2.9 on 2021-11-02 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Manager')], default=2),
        ),
    ]
