# Generated by Django 3.2.9 on 2021-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0007_auto_20211111_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsstatususerslocations',
            name='current_status',
            field=models.IntegerField(null=True),
        ),
    ]
