# Generated by Django 3.2.9 on 2021-11-11 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0008_logsstatususerslocations_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsstatususerslocations',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_fromuser_status_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
