# Generated by Django 3.2.9 on 2021-11-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0009_auto_20211102_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='manager_location',
            field=models.ForeignKey(limit_choices_to={'user_type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
