# Generated by Django 3.2.9 on 2021-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0009_logsstatususerslocations_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeesevents',
            name='plus_other',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
