# Generated by Django 3.2.9 on 2021-11-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0010_alter_location_manager_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_locations', to='monespace.location'),
        ),
    ]
