# Generated by Django 3.2.9 on 2021-11-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0011_auto_20211115_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeesevents',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monespace.recurringpattern'),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='max_num_occurrences',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
