# Generated by Django 3.2.9 on 2021-11-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0011_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_full_day',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_count', models.IntegerField()),
                ('max_num_occurrences', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('week_of_month', models.IntegerField()),
                ('day_of_month', models.IntegerField()),
                ('month_of_year', models.IntegerField()),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pattern', to='monespace.event')),
            ],
        ),
    ]
