# Generated by Django 3.2.9 on 2021-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0012_auto_20211126_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeesevents',
            name='time_from',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AddField(
            model_name='attendeesevents',
            name='time_to',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
