# Generated by Django 3.2.9 on 2021-11-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0012_auto_20211104_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpattern',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monespace.recurringpattern'),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='max_num_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='month_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='week_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
