# Generated by Django 3.2.9 on 2021-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0014_auto_20211104_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='separation_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
