# Generated by Django 3.2.9 on 2021-11-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0014_event_was_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='was_recurring_event_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monespace.event'),
        ),
    ]
