# Generated by Django 3.2.9 on 2021-11-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0015_alter_recurringpattern_separation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monespace.event'),
        ),
    ]
