# Generated by Django 3.2.9 on 2021-11-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0015_event_was_recurring_event_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='was_recurring',
        ),
    ]
