# Generated by Django 3.2.9 on 2021-11-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0016_alter_recurringpattern_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpattern',
            name='repeat_each_x',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
