# Generated by Django 3.2.9 on 2021-11-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0017_auto_20211127_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address_number',
        ),
    ]
