# Generated by Django 3.2.9 on 2021-11-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0018_auto_20211106_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
