# Generated by Django 3.2.9 on 2021-12-03 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0018_remove_location_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='test_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
