# Generated by Django 3.2.9 on 2021-11-08 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0019_alter_recurringpattern_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpattern',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='month_of_year',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='week_of_month',
        ),
        migrations.AlterField(
            model_name='location',
            name='manager_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
