# Generated by Django 3.2.9 on 2021-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0019_location_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='test_user',
            new_name='locations_managers',
        ),
    ]
