# Generated by Django 3.2.9 on 2021-12-03 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0021_rename_locations_managers_location_location_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_managers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
