# Generated by Django 3.2.9 on 2021-12-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0023_alter_location_location_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='manager_location',
        ),
    ]
