# Generated by Django 3.2.9 on 2021-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0025_event_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_distrib',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2021-12-08'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
