# Generated by Django 3.2.9 on 2021-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0026_auto_20211208_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2021-12-09'),
        ),
    ]
