# Generated by Django 3.2.9 on 2021-12-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0027_auto_20211209_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='statususerslocations',
            name='distrib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_status_user', to='monespace.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2021-12-10'),
        ),
    ]
