# Generated by Django 3.2.9 on 2021-12-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0028_auto_20211210_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsstatususerslocations',
            name='distrib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Logs_distrib_status_user', to='monespace.location'),
            preserve_default=False,
        ),
    ]
