# Generated by Django 3.2.9 on 2021-12-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0029_logsstatususerslocations_distrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsstatususerslocations',
            name='distrib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs_distrib_status_user', to='monespace.event'),
        ),
    ]
