# Generated by Django 3.2.9 on 2021-12-14 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0034_auto_20211214_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_users',
        ),
        migrations.AddField(
            model_name='message',
            name='to_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
