# Generated by Django 3.2.9 on 2021-12-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0035_auto_20211214_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='event',
            new_name='to_event',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='event_date',
            new_name='to_event_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='groups',
            new_name='to_event_group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='location',
            new_name='to_location',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='to_users',
            new_name='to_user',
        ),
    ]
