# Generated by Django 3.2.9 on 2021-12-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0040_auto_20211219_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pre_alert_non_attendees_nb_attendees',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='event',
            name='pre_alert_non_attendees_status',
            field=models.BooleanField(default=True),
        ),
    ]
