# Generated by Django 3.2.9 on 2021-12-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0042_auto_20211220_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
