# Generated by Django 3.2.9 on 2021-12-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monespace', '0044_auto_20211222_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_event_manger_group',
            new_name='to_event_manager_group',
        ),
    ]
